# Generated by Django 4.0.6 on 2022-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
